apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: x98d5542l-java-springboot
  janus-idp.io/tekton: x98d5542l-java-springboot
  backstage.io/kubernetes-id: x98d5542l-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: x98d5542l-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
